---
- name: "Example"
  outputDirectory: "output/"
  format: ["text"]
  immediateFirstRun: true
  # https://crontab.guru/every-30-minutes
  schedule: "*/5 * * * *"
  browser:
    attempts: 5
    flags: []
    headless: true
    height: 1080
    output:
      displayHeaderFooter: false
      fullPage: true
      landscape: false
      pdfFormat: "A4"
      printBackground: false
      quality: 100
      scale: 1
      textEncoding: utf8
    retryFactor: 1.3
    tabs: 1
    timeout: 60000
    verbose: true
    # https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options
    waitUntil: "domcontentloaded"
    width: 1920
  urls:
    - http://www.cnn.com/
  servePath: ""
