name: Deploy

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  push-image:
    # Name the Job
    name: Push Image
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=build_date::$(date -u +'%Y%m%d')
      # https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      # https://github.com/docker/login-action#github-packages-docker-registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push to ghcr.io
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker-image/debian/Dockerfile
          tags: |
            ghcr.io/${{ github.actor }}/webcron:canary
            ghcr.io/${{ github.actor }}/webcron:3.0.0
            ghcr.io/${{ github.actor }}/webcron:${{ github.sha }}
            ghcr.io/${{ github.actor }}/webcron:${{ github.run_id }}
            ghcr.io/${{ github.actor }}/webcron:${{ steps.prep.outputs.build_date }}
            docker.io/${{ github.actor }}/webcron:canary
            docker.io/${{ github.actor }}/webcron:3.0.0
            docker.io/${{ github.actor }}/webcron:${{ github.sha }}
            docker.io/${{ github.actor }}/webcron:${{ github.run_id }}
            docker.io/${{ github.actor }}/webcron:${{ steps.prep.outputs.build_date }}
          labels: |
            org.opencontainers.image.title=webcron IDE
            org.opencontainers.image.description=webcron Web IDE for Docker self-hosted development
            org.opencontainers.image.vendor=${{ github.actor }}
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.version=3.0.0
            org.opencontainers.image.url=${{ github.event.repository.clone_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.build_timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
