name: reviewdog
on: [pull_request]
jobs:
  # https://github.com/marketplace/actions/run-hadolint-with-reviewdog
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check

  # https://github.com/marketplace/actions/run-codespell-with-reviewdog
  codespell:
    name: runner / codespell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3
      - name: codespell
        uses: plettich/action-codespell@master
        with:
          github_token: ${{ secrets.github_token }}
